### ISSUE TITLE
More options to change host and port of perseus serve

### ISSUE THREAD

**Issue by Mazwak** [arctic-hen7/perseus#107]
Right now, host and port can be changed through environment HOST and PORT.

It would be nice to have more options :

- command line option
- dotenv/perseus.toml

Moreover, HOST and PORT are too generic, PERSEUS_HOST and PERSEUS_PORT would be better.

**Comment by arctic-hen7** [comment]
The new `-s/--serve` flag on `perseus export` takes command-line arguments for these, and I agree that it would be far better to use the same system on `perseus serve`. I'll introduce the command-line arguments for development usage, and they'll take precedence over the environment variables, but the reason the system is the way it is now is because of the final binary. When you run `perseus deploy`, you get a standalone binary that you run directly, without the abstraction of the Perseus CLI. I obviously don't want to bring something like `clap` into that, and I honestly want to avoid any argument parsing at all there, which is why I used environment variables. In development though, they are inconvenient.

As for the naming, I originally considered making them more specific in that way, though I decided to go with what other frameworks do (e.g. `create-react-app` uses `HOST` and `PORT`). However, I appreciate that these are inconvenient to specify in something like `.bashrc` because they'll likely impact other programs, so I'll make these less obnoxious in v0.4.0 (it's a breaking change).

With regards to `perseus.toml`, I think I'm going to say no to that, because it adds extra complexity that I don't think is necessary in terms of providing these arguments. If you want to set the host and port for all the Perseus apps you develop, you can set the environment variables somewhere like `.bashrc` (which will be easier with the name changes). If you just want to set them for a single project, you can use a command aliasing system like `make` or [Bonnie](https://github.com/arctic-hen7/bonnie).

How does that all sound to you @Mazwak?

**Comment by Mazwak** [comment]
### About my original request, that is « enhance perseus serve ».

Command-line would be nice but not mandatory. Some users are more used to options than to environment variables. It would be a QoL for them. Also, most (all ?) frameworks have those options.

I think names for the environment variables should not be generic. It could be both though. First PERSEUS_HOST, then HOST.

I think reading a ".env" file would be nice. File can be committed.
You clone, you launch perseus serve, and it listen where you expect it to.
I do agree that it is MUCH more work than reading the environment.
It’s ok not to implement it.

Bonnie is an ok solution.

### For perseus deploy or export

I do agree that less dependencies is better.

Using only HOST and PORT is ok, as you usually setup the env for your app.
I would even go as far as if --host/--port is used, host and port should be hardcoded, mainly for deploy.

**Comment by arctic-hen7** [comment]
As I said, I'll add the command line options and I'll change the environment variable names in v0.4.0. A `.env` file is not a standard thing outside the JS ecosystem to my knowledge, it's quite particular to NextJS, so I'm not that keen to implement that, it also makes the priorities system for conflicts overly complex in my opinion.

As for the deployed binary, I think hardcoding isn't an option because the binary should be as portable as possible, I'd prefer to stick to the environment variables there.

**Comment by arctic-hen7** [comment]
This is done, and will be released in v0.3.2. The `HOST`/`PORT` environment variables are now deprecated, and I'll remove them altogether in the next major release.
