### ISSUE TITLE
Refactoring html_shell.rs to improve readability

### ISSUE THREAD

**Issue by Asha20** [arctic-hen7/perseus#108]
Hi, I was wondering if I could contribute to the project by helping improve general code quality?

I picked [this file](https://github.com/arctic-hen7/perseus/blob/main/packages/perseus/src/html_shell.rs) in particular as a starting point because it seemed rather small and self-contained, but if you have other suggestions please feel free to let me know.

Here are some of the things I feel could be improved:

- Remove code duplication [here](https://github.com/arctic-hen7/perseus/blob/4139df9d055be41c55b8b92abb831ee20ac60af5/packages/perseus/src/html_shell.rs#L86-L100) and [here](https://github.com/arctic-hen7/perseus/blob/4139df9d055be41c55b8b92abb831ee20ac60af5/packages/perseus/src/html_shell.rs#L145-L161).
- Use newtypes to enforce invariants present in comments [here](https://github.com/arctic-hen7/perseus/blob/4139df9d055be41c55b8b92abb831ee20ac60af5/packages/perseus/src/html_shell.rs#L105-L106) and [here](https://github.com/arctic-hen7/perseus/blob/4139df9d055be41c55b8b92abb831ee20ac60af5/packages/perseus/src/html_shell.rs#L57-L58).
- Try to improve readability of the numerous `format!` calls that embed other strings inside HTML fragments, probably by putting them in separate functions.

**Comment by arctic-hen7** [comment]
You're more than welcome to contribute, please go right ahead and open a PR! A very large portion of Perseus is fairly haphazardly written because of how many times I've needed to change things to add new features. I18n in particular turned things into a bit of a pigsty. Any refactoring is appreciated, thank you very much!

I will be doing a major refactor soon to close #4, but that's a little while away.
